### ISSUE TITLE
error while loading library(intansv)

### ISSUE THREAD

**Issue by rajanikanthnmsu** [venyao/intansv#1]
Hi

I am getting the following error when i load the intansv.

> library(intansv)
> Error in fetch(key) : 
>   lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/intansv/help/intansv.rdb' is corrupt
> In addition: Warning message:
> In fetch(key) : internal error -3 in R_decompress1
> Error in fetch(key) : 
>   lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/intansv/help/intansv.rdb' is corrupt
> In addition: Warning message:
> In fetch(key) : internal error -3 in R_decompress1

**Comment by venyao** [comment]
Please try the latest version of intansv at Github.
