### ISSUE TITLE
cannot read in the lumpy output

### ISSUE THREAD

**Issue by gunjangala** [venyao/intansv#2]
Hi,
I am not able to read-in the .vcf output file produced by lumpy. 
Any suggestions/ideas for making this work ?
Thanks.

**Comment by Asutu** [comment]
I have the same problem. It seems that intansv just works with lumpy version 0.2.8. I've got 0.2.13.
Suggestions for conversion between lumpy versions?

**Comment by venyao** [comment]
Please install the latest development version of intansv at http://www.bioconductor.org/packages/devel/bioc/html/intansv.html

To install, type the following commands in R:

```
source("http://bioconductor.org/biocLite.R")  
useDevel()
biocLite("intansv")  
```

Or download the package to your computer and install the package using RStudio.
