### ISSUE TITLE
merge SV detected using Pacbio sequence

### ISSUE THREAD

**Issue by liufy11** [venyao/intansv#7]
Hello,
        with the emergency of  the third generation sequencing technology ,many softwares have been developed to detect SV using the the third generation sequence ,such as Sniffle, pbsv, svim. Can I merge the SV results detected by the above softwares ?

**Comment by venyao** [comment]
For now, you must converted the output of these software into a standard format accepted by intansv.

The standard format file should contain 6 columns as follows and should be read into R as a data frame. Please check the vignette of intansv.
`chromosome` `pos1` `pos2` `size` `type` `methods`

We will incorprate functions to process the output of some of these softwares into intansv in the future.
