### ISSUE TITLE
Cannot access help manual or vignettes

### ISSUE THREAD

**Issue by nikitagambhir** [venyao/intansv#9]
I am not able to access any resource to understand how to use this package. When I click on the link provided for "Overview of intansv" below "Help Manual", it gives me an error. Can you please provide some examples and documentation on how to use this package?
<img width="1368" alt="Screen Shot 2020-05-20 at 7 11 41 PM" src="https://user-images.githubusercontent.com/25594159/82510032-2a7d8b80-9acf-11ea-9af1-0be1e8509fc3.png">

**Comment by venyao** [comment]
Sorry. The help manual was missing in the last update and was deposited in the current release. Please check https://github.com/venyao/intansv/blob/master/intansvOverview.pdf
